tests:
    image: alpine:3.8
    before_script:
        - apk add --no-cache --update python3 python3-dev make gcc musl-dev
        - pip3 install -r requirements.txt --no-cache-dir
    script:
        - make lint
        - make tests