sudo: true
language: python
python:
    - "3.6"
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_fe78e4c36734_key -iv $encrypted_fe78e4c36734_iv -in gce.json.enc -out gce.json -d
install:
    - pip install -r requirements.txt
stages:
  - name: tests
  - name: deploy
jobs:
    include:
        - stage: tests
          script: make lint
        - stage: tests
          env:
            - GOOGLE_APPLICATION_CREDENTIALS=gce.json
          script: make tests
        - stage: deploy
          provider: gae
          project: filesave-215811
          keyfile: gce.json
          config: ./src/app.yaml
          default: true
          verbosity: debug
          on: master
