language: python
python:
    - "3.6"
before_install:
    - openssl aes-256-cbc -K $encrypted_fe78e4c36734_key -iv $encrypted_fe78e4c36734_iv -in service-account.json.enc -out service-account.json -d
stages:
  - name: tests
  - name: deploy
jobs:
    include:
        - stage: tests
          install: pip install -r requirements.txt
          script: make lint
        - stage: tests
          install: pip install -r requirements.txt
          env:
            - GOOGLE_APPLICATION_CREDENTIALS=service-account.json
          script: make tests
        - stage: deploy
          script: skip
          deploy:
            provider: gae
            skip_cleanup: true
            keyfile: service-account.json
            config: src/app.yaml
            project: filesave-215811
            default: true
            on: master
