version: "3"
services:
    api:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        working_dir: /code
        environment: 
            API_MODE: devel
            GOOGLE_APPLICATION_CREDENTIALS: gce.json
        command: [ "make", "run" ]